# Generated by Django 5.1.5 on 2025-02-01 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit Card'), ('loan', 'Loan'), ('line_of_credit', 'Line of Credit'), ('mortgage', 'Mortgage')], max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('apr_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('overdraft_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_back', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('annual_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mortgage_type', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('variable', 'Variable')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bank_account',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='finance.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.institution'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='institution',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='finance.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='finance.transactioncategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
